apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
