apiVersion: v1
kind: PersistentVolume
metadata:
  name: multitool
  labels:
    volume-type: multitool
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/"
