apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multitool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume-type: multitool

